version: '2.3'

services:

# Elastic services
## Elasticsearch service
  elasticsearch:
    build: elasticsearch/.
    image: "ghcr.io/telekom-security/elasticsearch-wt:latest"

## Kibana service
  kibana:
    build: kibana/.
    image: "ghcr.io/telekom-security/kibana-wt:latest"

## Logstash service
  logstash:
    build: logstash/.
    image: "ghcr.io/telekom-security/logstash-wt:latest"

## Slack-Watchman service
  slack-watchman:
    build: slack-watchman/.
    image: "ghcr.io/telekom-security/slack-watchman:latest"
