version: '2.3'

services:

# Elastic services
## Elasticsearch service
  elasticsearch:
    build: elasticsearch/.
    image: "avicoder/elasticsearch-wt:latest"

## Kibana service
  kibana:
    build: kibana/.
    image: "avicoder/kibana-wt:latest"

## Logstash service
  logstash:
    build: logstash/.
    image: "avicoder/logstash-wt:latest"

## Runner service
  runner:
    build: runner/.
    image: "avicoder/runner-wt:latest"
