version: '2.3'

services:

# Elastic services
## Elasticsearch service
  elasticsearch:
    build: .
    container_name: elasticsearch
    stdin_open: true
    tty: true
    restart: always
    environment:
     - ES_JAVA_OPTS=-Xms2048m -Xmx2048m
     - ES_TMPDIR=/tmp
    cap_add:
     - IPC_LOCK
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 4g
    ports:
     - "127.0.0.1:9200:9200"
    image: "dtagdevsec/elasticsearch-wt:latest"
    volumes:
     - /data:/data
     - /data/elastic/certs:/usr/share/elasticsearch/config/certs

## Kibana service
  kibana:
    build: .
    container_name: kibana
    restart: always
    depends_on:
      elasticsearch:
        condition: service_healthy
    ports:
     - "5601:5601"
    environment:
      ELASTICSEARCH_USERNAME: kibana_system
      ELASTICSEARCH_PASSWORD: CHANGEME
      ELASTICSEARCH_OBJECTS_ENCRYPTION_KEY: CHANGEME
      ELASTICSEARCH_SECURITY_ENCRYPTION_KEY: CHANGEME
      ELASTICSEARCH_REPORTING_ENCRYPTION_KEY: CHANGEME
    image: "dtagdevsec/kibana-wt:latest"
    volumes:
     - /data/elastic/certs:/usr/share/kibana/config/certs

## Logstash service
  logstash:
    build: .
    container_name: logstash
    restart: always
    environment:
     - LS_JAVA_OPTS=-Xms2048m -Xmx2048m
    depends_on:
      elasticsearch:
        condition: service_healthy
    environment:
      ELASTICSEARCH_USERNAME: elastic
      ELASTICSEARCH_PASSWORD: CHANGEME
    image: "dtagdevsec/logstash-wt:latest"
    volumes:
     - /data:/data
#     - /root/watchtower/docker/logstash/dist/logstash.conf:/etc/logstash/conf.d/logstash.conf
