version: '2.3'

services:

## Kibana service
  kibana:
    build: .
    container_name: kibana
    restart: always
    ports:
     - "5601:5601"
    environment:
      SERVERNAME: localhost
      ELASTICSEARCH_USERNAME: kibana_system
      ELASTICSEARCH_PASSWORD: CHANGEME
    image: "avicoder/kibana-wt:latest"
    volumes:
     - /data/elastic/certs:/usr/share/kibana/config/certs
