version: '2.3'

networks:
  slack-watchman_local:

services:

# Slack-Watchman service
  slack-watchman:
    build: .
    container_name: slack-watchman
    restart: "no"
    networks:
     - slack-watchman_local
    environment:
     - SLACK_WATCHMAN_TOKEN=
       # The filename will be slack_watchman.log
     - SLACK_WATCHMAN_LOG_PATH=
     - SLACK_WATCHMAN_LOGFILE=/opt/slack-watchman/log/slack-watchman_slackoverload.json
     - SLACK_WATCHMAN_HOST=
     - SLACK_WATCHMAN_PORT=
       # [--users] [--channels] [--pii] [--financial] [--tokens] [--files] [--custom CUSTOM]
     - SLACK_WATCHMAN_QUERY=--all
       # --timeframe {d,w,m,a}
     - SLACK_WATCHMAN_TIMEFRAME=--timeframe a
    image: "ghcr.io/t3chn0m4g3/slack-watchman:latest"
    read_only: true
    volumes:
     - /data/slack-watchman/log:/opt/slack-watchman/log
