version: '2.3'

services:

## Logstash service
  logstash:
    build: .
    container_name: logstash
    restart: always
    environment:
     - LS_JAVA_OPTS=-Xms2048m -Xmx2048m
#    depends_on:
#      elasticsearch:
#        condition: service_healthy
    image: "ghcr.io/t3chn0m4g3/logstash:latest"
    volumes:
     - /data:/data
       #     - /root/tpotce/docker/elk/logstash/dist/logstash.conf:/etc/logstash/conf.d/logstash.conf
