version: '2.3'

services:

## Logstash service
  logstash:
    build: .
    container_name: logstash
    restart: always
    environment:
     - LS_JAVA_OPTS=-Xms2048m -Xmx2048m
    image: "avicoder/logstash-wt:latest"
    volumes:
     - /data:/data
#     - /root/watchtower/docker/logstash/dist/logstash.conf:/etc/logstash/conf.d/logstash.conf
